language: java

services:
- postgresql

before_install:
- src/test/ci/bin/setup-mongodb.sh
- src/test/ci/bin/setup-postgresql.sh

#sudo: required

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/
  - downloads

script:
-  mvn -e verify deploy

env:
- SPRING_PROFILES_ACTIVE=ci

