language: java

services:
- postgresql
#- mongodb


before_script:
- psql -c 'CREATE DATABASE orders;' -U postgres
- psql -c 'CREATE TABLE customers( id bigint not null, email varchar(255) not null );' -U postgres orders

sudo: required

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/

script:
-  mvn -e verify deploy

env:
- SPRING_PROFILES_ACTIVE=ci