language: java

services:
- postgresql

before_script:
- psql -c 'CREATE DATABASE orders;' -U postgres

sudo: required

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/

script:
-  mvn -e verify deploy

env:
- SPRING_PROFILES_ACTIVE=CI